### PR TITLE
Fixing the default locale problem

### LINKED ISSUE #138: Load default locale when Lang's Key Isn't there
Fixing This.

### PR DESCRIPTION
**Pull request by Deep-Codes**
Attempts to Fix #138

```js
const en  = {
  home: {
    name: 'Deep',
    newName: 'Bhade'
  }
}

const mr = {
 home: {
   name: 'खोल'
 }
}


const t = useLocale(mr , 'home' )
```
`t` would be :
```js
 home: {
   name: 'खोल',
   newName: 'Bhade'
 }
```

### CODE REVIEW

**Comment by shrihari689** [comment]
Just an idea 💡

Consider this one,

```js
const en  = {
  home: {
    name: 'Deep',
    newName: 'Bhade'
  }
} 
```

```js
const useLocale = (loc, type) => {
    return (key) => (languages[loc]?.[type]?.[key] || languages["EN"]?.[type]?.[key] || "");
}; 
```


```jsx
const translate = useLocale(locale, 'home');

return <div>{translate("newName") + translate("oldName")}</div>
// <div>Bhade</div>
```


Something like we can return a function and then call in the components instead of loading whole data in every component 🤔.

**Comment by Deep-Codes** [comment]
> Just an idea 💡
> 
> Consider this one,
> 
> ```js
> const en  = {
>   home: {
>     name: 'Deep',
>     newName: 'Bhade'
>   }
> } 
> ```
> 
> ```js
> const useLocale = (loc, type) => {
>     return (key) => (languages[loc]?.[type]?.[key] || languages["EN"]?.[type]?.[key] || "");
> }; 
> ```
> 
> ```js
> const translate = useLocale(locale, 'home');
> 
> return <div>{translate("newName") + translate("oldName")}</div>
> // <div>Bhade</div>
> ```
> 
> Something like we can return a function and then call in the components instead of loading whole data in every component 🤔.
> I am thinking this one as instead of `transParse()` 📍

Then we gotta change all translation placeholders which is a lot of unnecessary work, having all data into the component matches with the current API.

**Comment by shrihari689** [comment]
> Then we gotta change all translation placeholders which is a lot of unnecessary work, having all data into the component matches with the current API.

Cool 🚀 then let's proceed this itself 🎉

Looks good to me 📍

**Review by shrihari689 — APPROVED** [review]
Looks good to me 🎉📌

**Pull request merged**
