### PR TITLE
Add airtable API

### PR DESCRIPTION
**Pull request by viksit**
Add downvote/upvote to API
Add thumbs up/down icons to entity page for oxygen
Connect API

### CODE REVIEW

**Comment by viksit** [comment]
two things 

- the api keys arent working for me from .env for some reason. I've had to hardcode them for my own instance and made them dummy for this
- for each table you want upvote/downvote, will need to create a "UpVotes" and "DownVotes" column (Number, int) manually.

**Comment by viksit** [comment]
@bodhish

**Comment by Deep-Codes** [comment]
> two things
> 
> * the api keys arent working for me from .env for some reason. I've had to hardcode them for my own instance and made them dummy for this
> * for each table you want upvote/downvote, will need to create a "UpVotes" and "DownVotes" column (Number, int) manually.

we can add it via `GITHUB SECRETS`

**Comment by bodhish** [comment]
The API key will have to be updated on vercel

**Comment by shrihari689** [comment]
Hope we moved out of Airtable 📌

**Pull request closed without merging**
