### PR TITLE
Text Color Fix for State's districts list page

### PR DESCRIPTION
**Pull request by aayushsaini**
### **Changed the text's colour on the State's districts' list page for _optimal visibility_ in the dark mode.**

**Reason:**
When I first opened the website, it opened up in the dark mode and upon clicking on the states, the following texts: _(Districts' Name and title 'Search Result For')_ were not optimally visible on the dark mode. So as a concern for the people with weak eye sight, I have changed the colour of those texts for the optimal visibility and viewing experience on both dark and light mode.

Attaching images for the reference.

- **Updated Text Color(Dark)**Screenshot 2021-04-24 at 12 59 16 AM
- **Previous Text Color(Dark)**Screenshot 2021-04-24 at 12 59 47 AM

- **Updated Text Color(Light)**Screenshot 2021-04-24 at 1 00 50 AM
- **Previous Text Color(Light)**Screenshot 2021-04-24 at 1 00 59 AM

### CODE REVIEW

**Comment by karmakoder** [comment]
Dost, I dont see the color changes like ur description of the https://life-git-fork-aayushsaini-district-page-text-c-c9286c.vercel.app/delhi_(nct) is thr a browser cache issue we facing? thx for pitching in 🙇‍♂️ 

Screen Shot 2021-04-23 at 3 59 57 PM

**Comment by aayushsaini** [comment]
My bad, I believe I wasn't able to convey my changes properly, here I've highlighted the difference.
P.s. the difference is more noticeable on the mobile devices.

**Previous Text Color** Screenshot 2021-04-24 at 1 32 34 AM

**New Text Color** Screenshot 2021-04-24 at 1 32 29 AM

**Comment by Deep-Codes** [comment]
> My bad, I believe I wasn't able to convey my changes properly, here I've highlighted the difference.
> P.s. the difference is more noticeable on the mobile devices.
> 
> **Previous Text Color** Screenshot 2021-04-24 at 1 32 34 AM
> 
> **New Text Color** Screenshot 2021-04-24 at 1 32 29 AM
> 
> **Suggestion**: If possible then please add back those highlight colours on different types of supplies available in districts, it was easily approachable.
> 
> Thank you :)

Yeah those Icon Colors are back 😇.

**Review by Deep-Codes — CHANGES_REQUESTED** [review]
Use `Tailwind's` CSS classes for dark mode:
remove class on `section`
instead, add `dark-text-gray-400`

Something like this:

```jsx
<h1 className="mt-4 text-xl sm:text-2xl md:text-3xl text-gray-900 dark:text-gray-400 md:text-left">
```

then the also apply same class for the `district name span` tag.

**Comment by aayushsaini** [comment]
> Use `Tailwind's` CSS classes for dark mode:
> remove class on `section`
> instead, add `dark-text-gray-400`
> 
> Something like this:
> 
> ```js
> <h1 className="mt-4 text-xl sm:text-2xl md:text-3xl text-gray-900 dark:text-gray-400 md:text-left">
> ```
> 
> then also apply the same class for the `district name span` tag.

Updated as mentioned.

Changes Made:

- Removed Tailwind Css class (.text-gray-800) from the <section>
- Added dark:text-gray-800 classes inside the following:
  1. &lt;h1&gt; tag of 'Search Result For' 
  2. &lt;span&gt; tag for Districts' Name

**Review by Deep-Codes — APPROVED** [review]

**Comment by Deep-Codes** [comment]
> > Use `Tailwind's` CSS classes for dark mode:
> > remove class on `section`
> > instead, add `dark-text-gray-400`
> > Something like this:
> > ```js
> > <h1 className="mt-4 text-xl sm:text-2xl md:text-3xl text-gray-900 dark:text-gray-400 md:text-left">
> > ```
> > 
> > 
> > then also apply the same class for the `district name span` tag.
> 
> Updated as mentioned.
> 
> Changes Made:
> 
> * Removed Tailwind Css class (.text-gray-800) from the
> * Added dark:text-gray-800 classes inside the following:
>   
>   1. <h1> tag of 'Search Result For'
>   2. <span> tag for Districts' Name

Thanks!

**Pull request merged**
