### PR TITLE
#72 | created a common component for all entities

### PR DESCRIPTION
**Pull request by jenishjain**
Created a common component named `EntityCard` for all the different cards that were in place before, removed the old component files too

### CODE REVIEW

**Review by Deep-Codes — APPROVED** [review]
This is soo Well Implemented 🎉🎉🎉

**Comment by jenishjain** [comment]
have removed these files from git not sure why these are coming as conflicts here 🤔

**Comment by jenishjain** [comment]
> This is soo Well Implemented 🎉🎉🎉

Thanks 😬 . 
PS : my first open-source contribution feel free to point me out anywhere which need improvements

**Review by shrihari689 — APPROVED** [review]
Looks good to me 🎉

**Comment by Deep-Codes** [comment]
@jenishjain I added `key` in `plasma.js`.  and removed the 6 Card Files.

This is ready to be merged 🚀.

**Pull request merged**
