### PR TITLE
adding marathi translation

### PR DESCRIPTION
**Pull request by Deep-Codes**
This is a work in Progress.

Working along with Parents so Would Take Time. (Feel Free to Help Out).

Don't Merge it.

### CODE REVIEW

**Comment by riginoommen** [comment]
THis is awesome work

**Comment by Deep-Codes** [comment]
> THis is awesome work

Yey! Thanks 😅 🚀

**Comment by karmakoder** [comment]
> > THis is awesome work
> 
> Yey! Thanks 😅 🚀

@Deep-Codes shud i look for some marathi speakers/writers to help here?

**Comment by Deep-Codes** [comment]
> > > THis is awesome work
> > 
> > 
> > Yey! Thanks 😅 🚀
> 
> @Deep-Codes shud i look for some marathi speakers/writers to help here?

Yeah Sure that would be of great help😇

**Comment by karmakoder** [comment]
> > > > THis is awesome work
> > > 
> > > 
> > > Yey! Thanks 😅 🚀
> > 
> > 
> > @Deep-Codes shud i look for some marathi speakers/writers to help here?
> 
> Yeah Sure that would be of great help😇

which file specifically can I ask someone to look at?

**Comment by Deep-Codes** [comment]
> > > > > THis is awesome work
> > > > 
> > > > 
> > > > Yey! Thanks 😅 🚀
> > > 
> > > 
> > > @Deep-Codes shud i look for some marathi speakers/writers to help here?
> > 
> > 
> > Yeah Sure that would be of great help😇
> 
> @Deep-Codes which file specifically can I ask someone to look at?

[The Marathi. Folder](https://github.com/coronasafe/life/tree/marathi-trans/locales/mr)

Traslation Wanted : [About](https://github.com/coronasafe/life/blob/marathi-trans/locales/mr/about.js)

: [Campaign](https://github.com/coronasafe/life/blob/marathi-trans/locales/mr/campaign.js)

**Comment by karmakoder** [comment]
> > > > > > THis is awesome work
> > > > > 
> > > > > 
> > > > > Yey! Thanks 😅 🚀
> > > > 
> > > > 
> > > > @Deep-Codes shud i look for some marathi speakers/writers to help here?
> > > 
> > > 
> > > Yeah Sure that would be of great help😇
> > 
> > 
> > @Deep-Codes which file specifically can I ask someone to look at?
> 
> [The Marathi. Folder](https://github.com/coronasafe/life/tree/marathi-trans/locales/mr)
> 
> Traslation Wanted : [About](https://github.com/coronasafe/life/blob/marathi-trans/locales/mr/about.js)
> 
> : [Campaign](https://github.com/coronasafe/life/blob/marathi-trans/locales/mr/campaign.js)

Sorry dost havent been able to get anyone to help wid marathi yet.

**Comment by vandanabhandari** [comment]
@Deep-Codes Can you please merge whatever is there and then I can pull from upstream in my fork. I cannot edit in yours

**Comment by Deep-Codes** [comment]
Sure thing! Merging

**Pull request merged**
