### PR TITLE
LIFE-258: Added Map directions link in resources based on coordinates

### LINKED ISSUE #258: Add Google maps direction link based on coordinates available
**Is your feature request related to a problem? Please describe.**
Currently, we are fetching coordinates data(latitude and longitude) from API. It will be better if we have a link, on click of the same, maps will be opened with directions to that resource.

**Describe the solution you'd like**
I'm thinking of adding appropriate link with icon somewhere on the ResourceCard.jsx

### PR DESCRIPTION
**Pull request by tecnoder**
Fixes: [258](https://github.com/coronasafe/life/issues/258)

Added Google map Directions links based on coordinates(latitude & longitude) as shown below

Screenshot 2021-05-04 at 12 40 17 PM

### CODE REVIEW

**Comment by karmakoder** [comment]
@shrihari689 @bodhish @jitendraag can u kindly review and give feedback? Does ui look good?

**Review by karmakoder — DISMISSED** [review]

**Comment by shrihari689** [comment]
Cool Update 🎉

Everything looks good to me 📍

**Review by shrihari689 — COMMENTED** [review]
Why is the JSON files have changed? Can you please revert it back? 📍

**Comment by karmakoder** [comment]
Merging

**Pull request merged**
