### PR TITLE
New About page.

### PR DESCRIPTION
**Pull request by ProCode2**
Not done Yet might have to make the new navbar
image

### CODE REVIEW

**Comment by Deep-Codes** [comment]
> Not done Yet might have to make the new navbar
> image

I would make a navbar component I have to tweak the logo a bit.

**Comment by ProCode2** [comment]
Go ahead.

**Comment by bodhish** [comment]
@ProCode2 can you remove that border color and stick to the one in the image :D

**Comment by ProCode2** [comment]
border-gray-900 wasn't working when I tried. Doing that😅

**Comment by ProCode2** [comment]
@bodhish 
image

**Comment by bodhish** [comment]
Nice

**Pull request merged**
