### PR TITLE
adding i18n Indian Translations

### PR DESCRIPTION
**Pull request by Deep-Codes**
Work on #85

### CODE REVIEW

**Comment by shrihari689** [comment]
Going to learn how this work  👀
Meanwhile anyone who knows about this, review this PR. 📍
Let's ship ASAP! 🎉

**Comment by Deep-Codes** [comment]
> Going to learn how this work 👀
> Meanwhile anyone who knows about this, review this PR. 📍
> Let's ship ASAP! 🎉

Bodhi said to merge it. I waiting for some chores to complete.

**Comment by shrihari689** [comment]
Great Great ‼ 🔥 🎉

**Comment by bodhish** [comment]
Any blocker here?

**Comment by Deep-Codes** [comment]
> Any blocker here?

We were waiting for some Hindi Translations.

**Comment by bodhish** [comment]
@Deep-Codes ship out with what we have. Don't hold

**Comment by Deep-Codes** [comment]
Merging This 🚀

**Pull request merged**
