### PR TITLE
Campaign markdown

### LINKED ISSUE #155: Content change for campaign / donate page
Please add some basic para formatting and bullet, giving markdown content here to be updated : 

As of today, India is undergoing a severe second wave of COVID-19 with the world’s highest daily new cases. Hospitals and healthcare providers are running out of resources in the fight against COVID-19 and the situation on the ground is dire. Oxygen is critically required to treat patients affected with COVID-19, many of whom require hospitalization. However, there is a severe shortage of oxygen across hospitals in India.

We are raising funds to help procure and distribute oxygen concentrators across hospitals in need. These oxygen concentrators can save many thousands of lives and bolster much-needed resources for hospitals. They can also be used to treat outpatients, reducing the load on hospital beds and easing the stress faced by patients.

### How you can contribute:

Please donate at the links below.

#### Individuals in India*: 

These contributions are eligible for tax benefits for Indian citizens under Sec 80G

*Donate on Impactguru*: https://www.impactguru.com/fundraiser/oxygen

*Donate on Milaap*: https://milaap.org/fundraisers/Donate-for-Oxygen

#### Individuals in other countries: 
US citizens contributing >$1000 can avail tax exemptions for donations made on Milaap

*Donate on Milaap*: https://milaap.org/fundraisers/Donate-for-Oxygen. 

Create a supporting sub-campaign: https://www.ketto.org/fundraiser/Donateforoxygen

#### Organisations / CSR Funding

Individual large grants from India or other countries: For grants > Rs.7,50,000 or $10000, please write to us directly at shubha@swasthapp.org

Organization based or CSR Funding: To contribute as an organization from India or other countries, please write to us directly at shubha@swasthapp.org

Long term partners: You can also partner with Swasth.app on its longer term mission in accelerating digital health tool adoption across India through open source products. Please write to shubha@swasthapp.org to learn more.

### PR DESCRIPTION
**Pull request by Sandra3657**
Resolves #155

### CODE REVIEW

**Comment by Deep-Codes** [comment]
Screenshot 2021-04-29 at 8 00 18 PM

Can we get some margin in between the text?

**Review by Deep-Codes — APPROVED** [review]
This is Good, Merge it whenever done.

**Review by khavinshankar — APPROVED** [review]
looks good

**Review by khavinshankar — APPROVED** [review]
👍 looks nice

**Pull request merged**
