### PR TITLE
Refactor campaigns

### PR DESCRIPTION
**Pull request by Deep-Codes**
#216 

- [x] Fix Header Element Colors in Dark Mode

### CODE REVIEW

**Comment by arnabsen1729** [comment]
@Deep-Codes In dark mode, the headings have very low contrast. 

image

**Comment by karmakoder** [comment]
@Deep-Codes is the code change complete for this?

**Comment by Deep-Codes** [comment]
> @Deep-Codes is the code change complete for this?

Nope there's 1 thing fix needed (Check the Todo on Top)

**Comment by ProCode2** [comment]
> @Deep-Codes is the code change complete for this?

Nope

**Comment by Deep-Codes** [comment]
Yeah works @arnabsen1729  🚀

**Pull request merged**
