### PR TITLE
Upd: Styled the oxygen requirements page

### PR DESCRIPTION
**Pull request by arnabsen1729**
Co-Authored-by: Abhinandan Arya <abhinandanarya06122000@gmail.com>

Added OxygenCard.jsx 

image
image

### CODE REVIEW

**Comment by shrihari689** [comment]
Looking for the fix 📍

**Comment by ProCode2** [comment]
> I don't know how this is fixed 😶
> But the styles are working now 📍
> image
> 
> I followed this repo and added `jit` to tailwind 📌
> https://github.com/vercel/next.js/tree/canary/examples/with-tailwindcss

@shrihari689 how are you doing this?😯 Please check #84 as well!

**Comment by arnabsen1729** [comment]
@shrihari689 Thank you so much. @ProCode2 I think after this is merged if you pull the changes that will be fixed too.

**Review by Deep-Codes — APPROVED** [review]
Beautiful 🚀

**Pull request merged**
