### PR TITLE
🚀 Redesign Home Page and Refactor all Search Pages 🎨

### LINKED ISSUE #151: New UI for "Search Results" page
Users can easily find what they wanted by using the search bar . saving the time for goal completion of users.
also some filers to show "verified" and "Not verified" data separately.
[Link to the file](https://www.figma.com/file/5vTeIYUU4ikk02XaPmN4rg/Raksha-Covid?node-id=106%3A318)

search results page

### PR DESCRIPTION
**Pull request by shrihari689**
## Proposed Changes 🏅

- Added @screens to Tailwind to support Responsiveness 📱
- Redesign Home Page 🎨
- Change `MainLayout` Alignment 📐
- Generate Static Path for All States and Districts (before it was only for Active Districts) 📍
- Added some small UI Elements 🖌
- Created New Resource Card Component 📌

🧐 Note:
- I haven't deleted the old UI Components and its related stuffs. Because they can be used while migrating this Resource Card component to fit the new data structure. Also don't want to break things now as some functions will be used on other places. Let's ship the MVP 🚢
- Made all routes redirect (render) to the `Home` Component for sake of SEO and already shared links. 📍
- Everything is working fine at my end. Please also cross check all possible cases. 🔥
- Open for all Feedbacks and Changes 😊

Resolves #151 📍 is a part of #176 😼

### CODE REVIEW

**Comment by abhinandanarya06** [comment]
image

Please recover the search bar so that people don't have to view list of state and district and select them. 
Atleast typing search bar is very user friendly when whatever typed get front of us. 

You can add voice search too if you want XD. :)

**Comment by Deep-Codes** [comment]
This is a Great UI i am just pushing some stuff. So just wait.

**Comment by shrihari689** [comment]
@abhinandanarya06 
  
> Please recover the search bar so that people don't have to view list of state and district and select them.
 
I too thought this at first when @joelsajichacko suggested this UI in #151 📍 
But later I thought that instead of the current flow like 
[ Typing the state or district ] -> [Go to State or District Page] -> [Find the District (Scroll)] -> [Go to Specific Type of Resource] 
will be replacing with just a select where it is Alphabetically ordered and we filter out district based on the states. 🤔

I think it would reduce time. He / She can also easily find the district by typing the first character 📌 << Feeling for Mobile Users 😶 >>

* : confused *

**Comment by Deep-Codes** [comment]
> @abhinandanarya06
> 
> > Please recover the search bar so that people don't have to view list of state and district and select them.
> 
> I too thought this at first when @joelsajichacko suggested this UI in #151 📍
> But later I understood that instead of the current flow like
> [ Typing the state or district ] -> [Go to State or District Page] -> [Find the District (Scroll)] -> [Go to Specific Type of Resource]
> will be replacing with just a select where it is Alphabetically ordered and we filter out district based on the states. 🤔
> 
> I think it would reduce time. He / She can also easily find the district by typing the first character 📌 << Feeling for Mobile Users 😶 >>
> 
> * : confused *

Right

I also have some fair points I would say after done with some features (would take some hours).

**Comment by Deep-Codes** [comment]
Now the Last Part 😅

**Comment by joelsajichacko** [comment]
> Please recover the search bar so that people don't have to view list of state and district and select them.
> Atleast typing search bar is very user friendly when whatever typed get front of us.
> 
> You can add voice search too if you want XD. :)

WhatsApp Image 2021-04-29 at 1 14 29 AM


@shrihari689 @Deep-Codes @abhinandanarya06 **Anyway we are showing suggestions for districts and states.. 
our end users maybe in a hurry .. they may not have enough time to go through all our site. We need to show what they specifically want.. if they are looking for oxygen we should show them as quick as possible without making them do much effort in a simple way**

WhatsApp Image 2021-04-29 at 1 35 42 AM

**Why do we want to to show them these inactive components, if they only want to know helplines ? We should show them only what they want. Also all our end users may not be common people.. there maybe health volunteers/social activists/doctors/police etc. We have to keep them all in mind. Now if one of them wants to take a look at availabilty of (say)oxygen at another district or state . He/her has to come all the way back to the home for typing another state or district**

**Comment by Deep-Codes** [comment]
> > Please recover the search bar so that people don't have to view list of state and district and select them.
> > Atleast typing search bar is very user friendly when whatever typed get front of us.
> > You can add voice search too if you want XD. :)
> 
> WhatsApp Image 2021-04-29 at 1 14 29 AM
> 
> @shrihari689 @Deep-Codes @abhinandanarya06
> **Anyway we are showing suggestions for districts and states.. our end users maybe in a hurry .. they may not have enough time to go through all our site, there might be chance of error when typing(can be avoided by giving the users "options" to select, like a dropdown). We need to show what they specifically want.. if they are looking for oxygen we should show them as quick as possible without making them do much effort in a simple way**
> 
> WhatsApp Image 2021-04-29 at 1 35 42 AM
> 
> **Why do we want to to show them these inactive components, if they only want to know helplines ? We should show them only what they want. Also all our end users may not be common people.. there maybe health volunteers/social activists/doctors/police etc. We have to keep them all in mind. Now if one of them wants to take a look at availabilty of (say)oxygen at another district or state . He/she has to come all the way back to the home for typing another state or district**
> 
> Why should we take people to inner pages to just show we don't have the data they are seeking. If we dont have data of some districts or any specific resources (We should disable the the options in the dropdown).

Another Point is The Scope of Typo is 0

And We can make way less API calls to Twitter

**Comment by Deep-Codes** [comment]
I am done with my Changes.

**Comment by Deep-Codes** [comment]
I am done from here @shrihari689 carry one 🚀

**Comment by shrihari689** [comment]
It's ready to merge 📍

**Review by Deep-Codes — APPROVED** [review]

**Comment by Deep-Codes** [comment]
Wait

**Pull request merged**
