### PR TITLE
revert index page and add selector to state

### PR DESCRIPTION
**Pull request by Deep-Codes**
# ⚠️ DON'T MERGE IT ⚠️

### CODE REVIEW

**Comment by ProCode2** [comment]
Shows showing live `tweet results for "" `
Screenshot 2021-04-29 at 6 11 18 PM

**Comment by Deep-Codes** [comment]
> Shows showing live `tweet results for "" `
> Screenshot 2021-04-29 at 6 11 18 PM

it's updated in the newest preview

**Comment by ProCode2** [comment]
Perfect!

**Comment by Deep-Codes** [comment]
@shrihari689 I don't see any problems.

**Comment by ProCode2** [comment]
Give the `Result` and `Twitter` tabs a fixed height so that the footer doesn't jump when changing the tab

**Comment by Deep-Codes** [comment]
> Give the `Result` and `Twitter` tabs a fixed height so that the footer doesn't jump when changing the tab

On it I was wondering why that happens

**Comment by shrihari689** [comment]
On it 🔥

**Comment by shrihari689** [comment]
Could find a workaround as well 😪

**Comment by Deep-Codes** [comment]
Yes let's just get this running

**Comment by ProCode2** [comment]
just had to add a min height to a parent div 😅

**Pull request merged**
