### PR TITLE
Tabs change

### PR DESCRIPTION
**Pull request by peeyush14goyal**
Tab changes to Twitter when we show twitter results.
Other changes are by Prettier

### CODE REVIEW

**Comment by karmakoder** [comment]
@peeyush14goyal can u kindly look at the conflicts?

**Comment by peeyush14goyal** [comment]
@karmakoder Sure

**Comment by peeyush14goyal** [comment]
@karmakoder Prettier issues were there. Done

**Comment by karmakoder** [comment]
> @karmakoder Prettier issues were there. Done

thx @peeyush14goyal github still shows file conflicts for 3 jsons. can that be ignored?

**Comment by peeyush14goyal** [comment]
@karmakoder Merge #236 before merging this. Then issues will be resolved

**Pull request merged**
